### ISSUE TITLE
我的 cordova 8.0.0 安装和编译均失败

### ISSUE THREAD

**Issue by chaohui2** [GiterLab/cordova-plugin-acmp#9]
目前安装插件过程中出现一下问题:
安装问题:找不到AndroidManifest.xml 文件,log显示其查询的路径为/platforms/android/AndroidManifest.xml  而不是/platforms/android/app/src/main/AndroidManifest.xml  
编译问题:插件提供的libs目录没有自动导入至platforms/android 下,导致编译失败

安装问题我在他查找的目录复制一个AndroidManifest 文件,安装成功后手动复制回原目录
编译时的问题我手动复制libs目录

**Comment by ChaoHui123** [comment]
可以提供一下目前插件支持的cordova版本吗,或者其他解决方案,
谢谢

**Comment by ChaoHui123** [comment]
将cordova android版本从7.0降级6.0后安装解决问题
`cordova platform remove android
cordova platform add android@6.3.0 `

**Comment by MWangxj** [comment]
cordova8.0更改了android的mainfest.xml文件的位置，故安装失败
